#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
测试知识图谱文件构建器 / Test Knowledge Graph File Builder

这个脚本测试 build_kg_example.py 生成的知识图谱文件是否符合RecBole的格式要求。
This script tests if the knowledge graph files generated by build_kg_example.py 
meet RecBole's format requirements.
"""

import os
import sys


def test_file_exists(file_path):
    """测试文件是否存在 / Test if file exists"""
    if os.path.exists(file_path):
        print(f"✓ 文件存在 / File exists: {file_path}")
        return True
    else:
        print(f"✗ 文件不存在 / File not found: {file_path}")
        return False


def test_kg_file_format(file_path):
    """
    测试 .kg 文件格式 / Test .kg file format
    
    检查:
    1. 第一行是否为正确的头部
    2. 是否使用制表符分隔
    3. 每行是否有3个字段
    """
    print(f"\n测试知识图谱文件格式 / Testing KG file format: {file_path}")
    
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    # 检查第一行头部
    expected_header = "head_id:token\trelation_id:token\ttail_id:token\n"
    if lines[0] != expected_header:
        print(f"  ✗ 头部格式错误 / Header format incorrect")
        print(f"    期望 / Expected: {repr(expected_header)}")
        print(f"    实际 / Actual: {repr(lines[0])}")
        return False
    
    print("  ✓ 头部格式正确 / Header format correct")
    
    # 检查数据行
    for i, line in enumerate(lines[1:], start=2):
        if line.strip():  # 跳过空行
            fields = line.strip().split('\t')
            if len(fields) != 3:
                print(f"  ✗ 第{i}行字段数不正确 / Line {i} has incorrect number of fields: {len(fields)}")
                print(f"    内容 / Content: {line.strip()}")
                return False
    
    print(f"  ✓ 所有 {len(lines)-1} 行数据格式正确 / All {len(lines)-1} data rows format correct")
    return True


def test_link_file_format(file_path):
    """
    测试 .link 文件格式 / Test .link file format
    
    检查:
    1. 第一行是否为正确的头部
    2. 是否使用制表符分隔
    3. 每行是否有2个字段
    """
    print(f"\n测试链接文件格式 / Testing link file format: {file_path}")
    
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    # 检查第一行头部
    expected_header = "item_id:token\tentity_id:token\n"
    if lines[0] != expected_header:
        print(f"  ✗ 头部格式错误 / Header format incorrect")
        print(f"    期望 / Expected: {repr(expected_header)}")
        print(f"    实际 / Actual: {repr(lines[0])}")
        return False
    
    print("  ✓ 头部格式正确 / Header format correct")
    
    # 检查数据行
    for i, line in enumerate(lines[1:], start=2):
        if line.strip():  # 跳过空行
            fields = line.strip().split('\t')
            if len(fields) != 2:
                print(f"  ✗ 第{i}行字段数不正确 / Line {i} has incorrect number of fields: {len(fields)}")
                print(f"    内容 / Content: {line.strip()}")
                return False
    
    print(f"  ✓ 所有 {len(lines)-1} 行数据格式正确 / All {len(lines)-1} data rows format correct")
    return True


def test_file_content(kg_file, link_file):
    """
    测试文件内容一致性 / Test file content consistency
    
    检查:
    1. .link 文件中的 entity_id 应该在 .kg 文件中存在
    """
    print(f"\n测试文件内容一致性 / Testing file content consistency")
    
    # 读取 .kg 文件中的所有实体
    entities_in_kg = set()
    with open(kg_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()[1:]  # 跳过头部
        for line in lines:
            if line.strip():
                fields = line.strip().split('\t')
                entities_in_kg.add(fields[0])  # head_id
                entities_in_kg.add(fields[2])  # tail_id
    
    # 读取 .link 文件中的实体
    entities_in_link = set()
    with open(link_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()[1:]  # 跳过头部
        for line in lines:
            if line.strip():
                fields = line.strip().split('\t')
                entities_in_link.add(fields[1])  # entity_id
    
    # 检查 .link 中的实体是否都在 .kg 中
    missing_entities = entities_in_link - entities_in_kg
    if missing_entities:
        print(f"  ✗ .link 文件中有 {len(missing_entities)} 个实体在 .kg 文件中不存在")
        print(f"    / {len(missing_entities)} entities in .link file are not found in .kg file")
        print(f"    缺失实体 / Missing entities: {missing_entities}")
        return False
    else:
        print(f"  ✓ .link 文件中的所有 {len(entities_in_link)} 个实体都在 .kg 文件中存在")
        print(f"    / All {len(entities_in_link)} entities in .link file exist in .kg file")
        return True


def main():
    """主测试函数 / Main test function"""
    print("="*80)
    print("知识图谱文件格式测试 / Knowledge Graph File Format Test")
    print("="*80)
    
    # 测试电影示例 / Test movie example
    print("\n" + "-"*80)
    print("测试电影示例 / Testing Movie Example")
    print("-"*80)
    
    movie_kg = './dataset/movie_example/movie_example.kg'
    movie_link = './dataset/movie_example/movie_example.link'
    
    all_passed = True
    
    if test_file_exists(movie_kg):
        if not test_kg_file_format(movie_kg):
            all_passed = False
    else:
        all_passed = False
    
    if test_file_exists(movie_link):
        if not test_link_file_format(movie_link):
            all_passed = False
    else:
        all_passed = False
    
    if os.path.exists(movie_kg) and os.path.exists(movie_link):
        if not test_file_content(movie_kg, movie_link):
            all_passed = False
    
    # 测试商品示例 / Test product example
    print("\n" + "-"*80)
    print("测试商品示例 / Testing Product Example")
    print("-"*80)
    
    product_kg = './dataset/product_example/product_example.kg'
    product_link = './dataset/product_example/product_example.link'
    
    if test_file_exists(product_kg):
        if not test_kg_file_format(product_kg):
            all_passed = False
    else:
        all_passed = False
    
    if test_file_exists(product_link):
        if not test_link_file_format(product_link):
            all_passed = False
    else:
        all_passed = False
    
    if os.path.exists(product_kg) and os.path.exists(product_link):
        if not test_file_content(product_kg, product_link):
            all_passed = False
    
    # 输出测试结果 / Output test results
    print("\n" + "="*80)
    if all_passed:
        print("✓ 所有测试通过! / All tests passed!")
        print("="*80)
        return 0
    else:
        print("✗ 部分测试失败 / Some tests failed")
        print("="*80)
        return 1


if __name__ == '__main__':
    sys.exit(main())
